### ISSUE TITLE
Client secrets not hashed

### ISSUE THREAD

**Issue by KorvinSzanto** [concretecms/concrete_api_proposal_2022#2]
Client secrets should be hashed in the database and verified using `password_verify`. The ClientRepository wrapper included here does handle hashed passwords, but we rely on them being not hashed in the swagger UI and we should never have them not hashed.

**Comment by aembler** [comment]
Yes, this is done by design. See the code comment here:

        // We also need to update our Client Repository – the core version always assumes that the client secret
        // is hashed. But for convenience in this particular setup I do NOT want to hash it because I want to
        // allow it to be passed to our Swagger UI (Note: not for use with production)

Basically, for the purposes of this package, we want to be able to pass the client id and secret to the Swagger UI documentation to make it easy to authenticate requests and test the API. This is not something we'll merge back into the core.
